---

- name: Del Old Docker to prevent conflicts (Recommends from docker.io) with full list in console
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  loop: "{{ docker_old_packages }}"

- name: Install Prerequiestes
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ docker_prerequiestes_packages }}"


###Old usage
#- name: Add Docker GPG Key
#  ansible.builtin.apt_key:
#    url: "{{ docker_key_url }}"
#    state: present

#- name: Add specified repository into sources list using specified filename
#  ansible.builtin.apt_repository:
#    repo: "{{ docker_repo_url }}"
#    state: present
#    filename: docker


- name: Download docker gpg key
  ansible.builtin.get_url:
    url: "{{ docker_key_url }}"
    dest: /etc/apt/keyrings/docker.asc

- name: Set permissions on downloaded gpg key
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add specified repository into sources list using specified GPG key
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    filename: docker

- name: Check docker group exist
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user to Docker group without excluding from another groups (append = yes)
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ users_add_to_docker }}"