---
- name: Create docker compose for LEMP from template
  ansible.builtin.template:
    src: "docker-compose.j2"
    dest: "{{ lemp_node_docker_compose_app }}/docker-compose.yml"
    mode: '0600'
    owner: root
    group: root
  register: __lemp_node_docker_compose_file

- name: Create Nginx site conf from template
  ansible.builtin.template:
    src: "nginx-example-site.j2"
    dest: "{{ lemp_node }}/nginx/conf.d/test_site.conf"
    mode: '0600'
    owner: root
    group: root
  register: __lemp_nginx_site_conf_file

- name: Create test_connection.php from template
  ansible.builtin.template:
    src: "test_connection.j2"
    dest: "{{ lemp_node_docker_compose_app }}/files/example-site/test_connection.php"
    mode: '0644'
    owner: root
    group: root
  register: __lemp_nginx_site_conf_file

- name: Copy required files
  ansible.builtin.copy:
    src: ./
    dest: "{{ lemp_node_docker_compose_app }}/files"

- name: Restart docker compose for LEMP
  community.docker.docker_compose_v2:
    project_src: "{{ lemp_node_docker_compose_app }}"
    state: present
    files:
      - docker-compose.yml
  register: __output_lemp_docker_restart
#  when: __lemp_node_docker_compose_file.changed

- name: Debug restart docker
  ansible.builtin.debug:
    var: __output_lemp_docker_restart
