---
- name: Down docker compose for LEMP
  community.docker.docker_compose_v2:
    project_src: "{{ lemp_node_docker_compose_app }}"
    state: absent
    files:
      - docker-compose.yml
  register: __output_lemp_down

- name: Show results down
  ansible.builtin.debug:
    var: __output_lemp_down

- name: Delete LEMP dirs
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop:
    - { path: "{{ lemp_node_docker_compose_app }}" }
    - { path: "{{ lemp_node }}" }
