---
- name: Import tasks for prepare folders
  ansible.builtin.import_tasks:
    file: "00-prepare.yml"
  tags:
    - lemp-docker


- name: Import tasks for deploy apps
  ansible.builtin.import_tasks:
    file: "01-deploy-apps.yml"
  tags:
    - lemp-docker

- name: Import tasks for delete LEMP in docker from host
  ansible.builtin.import_tasks:
    file: "99-delete-app.yml"
  tags:
    - never
    - lemp-docker-node-clean
  when:
    - "'lemp-docker-node-clean' in ansible_run_tags"


