---

- name: Stop docker and disable it
  ansible.builtin.service:
    name: docker
    state: stopped
    enabled: no

- name: Remove Docker
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  loop:
    "{{ docker_install_packages }}"

- name: Remove Docker GPG Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: absent


- name: Remove specified repository into sources list using specified filename
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: absent
    filename: docker

- name: Check docker group exist and delete it
  ansible.builtin.group:
    name: docker
    state: absent

- name: Clean Apt
  ansible.builtin.apt:
    autoremove: true
    autoclean: true

